//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeGaverbeekProject.Domain.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gaverbeek_syncEntities : DbContext
    {
        public gaverbeek_syncEntities()
            : base("name=gaverbeek_syncEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorieen> categorieen { get; set; }
        public virtual DbSet<klanten> klanten { get; set; }
        public virtual DbSet<klanten_adressen> klanten_adressen { get; set; }
        public virtual DbSet<klanten_cat_kort> klanten_cat_kort { get; set; }
        public virtual DbSet<klanten_lever_kort> klanten_lever_kort { get; set; }
        public virtual DbSet<klanten_producten> klanten_producten { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<producten> producten { get; set; }
        public virtual DbSet<promoties> promoties { get; set; }
    }
}
