//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeGaverbeekProject.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class klanten_producten
    {
        public long klantprod_id { get; set; }
        public int klantprod_klant_id { get; set; }
        public int klantprod_prod_id { get; set; }
        public Nullable<decimal> klantprod_prijs { get; set; }
        public Nullable<decimal> klantprod_korting { get; set; }
        public sbyte klantprod_vasteprijs { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string modified_by { get; set; }
    }
}
