//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeGaverbeekProject.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class klanten_lever_kort
    {
        public int klantlever_id { get; set; }
        public Nullable<int> klantlever_klant_id { get; set; }
        public Nullable<int> klantlever_lever_id { get; set; }
        public Nullable<decimal> klantlever_korting { get; set; }
        public Nullable<decimal> klantlever_korting_extra { get; set; }
        public Nullable<System.DateTime> klantlever_van { get; set; }
        public Nullable<System.DateTime> klantlever_tot { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string modified_by { get; set; }
    }
}
