//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeGaverbeekProject.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class producten
    {
        public int prod_id { get; set; }
        public Nullable<int> prod_nummer { get; set; }
        public string prod_code { get; set; }
        public string prod_benaming { get; set; }
        public Nullable<decimal> prod_vkp { get; set; }
        public Nullable<bool> prod_vkp_excl { get; set; }
        public Nullable<bool> prod_aantal_decim { get; set; }
        public Nullable<int> prod_btw_code { get; set; }
        public string prod_eenheid { get; set; }
        public Nullable<bool> prod_besteh_idem_vkpeh { get; set; }
        public string prod_type { get; set; }
        public Nullable<bool> prod_vrije_code { get; set; }
        public Nullable<bool> prod_code_actief { get; set; }
        public string prod_opmerkingen { get; set; }
        public Nullable<int> prod_cat_id { get; set; }
        public Nullable<int> prod_lever_id { get; set; }
        public string prod_lever_code { get; set; }
        public string prod_lever_benaming { get; set; }
        public Nullable<int> prod_extra_prod { get; set; }
        public Nullable<decimal> prod_extra_aantal { get; set; }
        public Nullable<bool> prod_boo_prijs_vast { get; set; }
        public Nullable<bool> prod_boo_include_hist { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string modified_by { get; set; }
    }
}
