//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeGaverbeekProject.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class promoties
    {
        public long prom_id { get; set; }
        public int prom_prod_id { get; set; }
        public Nullable<decimal> prom_prijs { get; set; }
        public Nullable<decimal> prom_korting { get; set; }
        public Nullable<System.DateTime> prom_van { get; set; }
        public Nullable<System.DateTime> prom_tot { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string modified_by { get; set; }
    }
}
